# Generated by Django 5.1.2 on 2025-03-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('', 'Select a position'), ('Accountant', 'Accountant'), ('Analyst', 'Analyst'), ('Developer', 'Developer'), ('Designer', 'Designer'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('Specialist', 'Specialist'), ('Technician', 'Technician')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_employees', to='app.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
